import { Link } from 'react-router-dom';
import LegalPage from '../../components/LegalPage';
import { LEGAL_CONTACT_EMAIL, LEGAL_OPERATOR } from '../../constants/legal';

const sections = [
  {
    heading: 'Who we are and what Recovia is',
    body: (
      <>
        <p>
          Recovia is a loan-recovery decision-support tool operated by {LEGAL_OPERATOR} ("we", "us"). It estimates
          recovery risk, suggests recovery strategies and drafts borrower communications.
        </p>
        <p>
          <strong>Recovia is not a lender, bank, NBFC, credit bureau or recovery agency</strong>, and it is not
          regulated by the Reserve Bank of India. It does not make credit decisions and does not contact borrowers.
        </p>
      </>
    ),
  },
  {
    heading: 'Accepting these terms',
    body: (
      <p>
        By creating an account or using the signed-in features you agree to these Terms, our{' '}
        <Link to="/privacy">Privacy Policy</Link> and our <Link to="/responsible-recovery">Responsible Recovery</Link>{' '}
        guidelines. If we change them materially we will ask you to accept the new version before you continue. You
        must be at least 18 years old, and if you use Recovia for an organisation, you confirm you are authorised to
        bind it.
      </p>
    ),
  },
  {
    heading: 'Risk scores and AI content are estimates, not decisions',
    body: (
      <>
        <p>
          Risk scores come from a statistical model trained on a limited dataset. AI case briefs are generated by a
          third-party large language model and can be incomplete or wrong. Asset classifications follow RBI's SMA/NPA
          days-past-due bands and are only as accurate as the data you enter.
        </p>
        <ul>
          <li>Review every score, strategy and draft message before acting on it.</li>
          <li>A qualified person must make any decision affecting a borrower, including escalation or legal action.</li>
          <li>Do not rely on Recovia as legal, financial or regulatory advice.</li>
        </ul>
      </>
    ),
  },
  {
    heading: 'Your responsibilities for borrower data',
    body: (
      <ul>
        <li>
          Only enter personal data about borrowers that you are lawfully permitted to process, for example as, or on
          behalf of, the lender to whom the debt is owed.
        </li>
        <li>You are responsible for the accuracy of the data you enter and for complying with applicable law.</li>
        <li>
          Follow RBI's fair practices and recovery-agent directions whenever you contact a borrower, as summarised in
          our <Link to="/responsible-recovery">Responsible Recovery</Link> page.
        </li>
      </ul>
    ),
  },
  {
    heading: 'Acceptable use',
    body: (
      <>
        <p>You must not:</p>
        <ul>
          <li>use Recovia to harass, threaten, shame or intimidate anyone, or to discriminate unlawfully;</li>
          <li>create multiple accounts, share accounts, or otherwise try to get around usage limits;</li>
          <li>scrape, overload, reverse-engineer or probe the service, or access it by automated means;</li>
          <li>upload data you have no right to use, or anything unlawful or malicious.</li>
        </ul>
        <p>We may suspend or close accounts that break these rules.</p>
      </>
    ),
  },
  {
    heading: 'AI features and usage limits',
    body: (
      <p>
        AI case briefs are only available to signed-in users who have accepted these Terms. Each account can generate
        up to <strong>5 AI briefs in any rolling 24-hour period</strong>, and a service-wide daily limit also applies.
        AI features may be unavailable at times, and we may change limits to keep the service sustainable.
      </p>
    ),
  },
  {
    heading: 'Your account',
    body: (
      <p>
        Keep your sign-in details secure and tell us promptly about any unauthorised use. You are responsible for
        activity under your account. You can stop using Recovia at any time and ask us to delete your account and
        data as described in the <Link to="/privacy">Privacy Policy</Link>.
      </p>
    ),
  },
  {
    heading: 'Intellectual property',
    body: (
      <p>
        We own the Recovia software, models and design. You keep your rights in the data you enter and grant us the
        permission we need to process it to provide the service.
      </p>
    ),
  },
  {
    heading: 'No warranty and limitation of liability',
    body: (
      <p>
        Recovia is provided "as is" and "as available", without warranties of accuracy, availability or fitness for a
        particular purpose. To the maximum extent permitted by law, we are not liable for indirect or consequential
        losses, or for decisions made using Recovia's output. Nothing in these Terms limits liability that cannot be
        limited under applicable law.
      </p>
    ),
  },
  {
    heading: 'Changes, termination and governing law',
    body: (
      <p>
        We may update these Terms. Material changes require your fresh acceptance. We may suspend or end the service
        or your access, for example for misuse. These Terms are governed by the laws of India, and courts in India have
        jurisdiction over disputes.
      </p>
    ),
  },
  {
    heading: 'Contact',
    body: (
      <p>
        Questions about these Terms: <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>.
      </p>
    ),
  },
];

export default function Terms() {
  return (
    <LegalPage
      title="Terms & Conditions"
      intro="These terms govern your use of Recovia's signed-in features: saved cases, risk history and AI case briefs. The public risk predictor can be used without an account."
      sections={sections}
    />
  );
}
